

services:

  api:
    build: .
    container_name: jarvis_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - /Users/nikhi/Downloads/olist:/app/datasets/olist
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/intelligent_dictionary
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    env_file:
      - .env

    depends_on:
      - db
      - redis
    restart: always

  worker:
    build: .
    container_name: jarvis_worker
    command: celery -A app.core.celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/intelligent_dictionary
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: ankane/pgvector
    container_name: jarvis_db
    environment:
      POSTGRES_DB: intelligent_dictionary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
    - .env

    restart: always

  redis:
    image: redis:7
    container_name: jarvis_redis
    ports:
      - "6379:6379"
    restart: always
  
volumes:
  postgres_data:

  
