version: '3.9'

services:
  postgres:
    image: ankane/pgvector
    container_name: jarvis_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: intelligent_dictionary
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
