"""add_namespace_to_vectors

Revision ID: 75b0f6c97100
Revises: db9c0ab3b17b
Create Date: 2026-03-24 08:13:47.891362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b0f6c97100'
down_revision: Union[str, Sequence[str], None] = 'db9c0ab3b17b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentation', sa.Column('connection_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'documentation', 'source_connections', ['connection_id'], ['id'])
    op.add_column('embeddings', sa.Column('connection_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'embeddings', 'source_connections', ['connection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.drop_column('embeddings', 'connection_id')
    op.drop_constraint(None, 'documentation', type_='foreignkey')
    op.drop_column('documentation', 'connection_id')
    # ### end Alembic commands ###
