"""add_source_connections

Revision ID: db9c0ab3b17b
Revises: 20260324_features
Create Date: 2026-03-24 08:10:11.704585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db9c0ab3b17b'
down_revision: Union[str, Sequence[str], None] = '20260324_features'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('db_type', sa.String(), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('schemas_name_key'), 'schemas', type_='unique')
    op.create_unique_constraint('unique_schema_per_connection', 'schemas', ['name', 'connection_id'])
    op.create_foreign_key(None, 'schemas', 'database_connections', ['connection_id'], ['id'])
    op.alter_column('tables', 'row_count',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tables', 'row_count',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_constraint(None, 'schemas', type_='foreignkey')
    op.drop_constraint('unique_schema_per_connection', 'schemas', type_='unique')
    op.create_unique_constraint(op.f('schemas_name_key'), 'schemas', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_table('source_connections')
    # ### end Alembic commands ###
